POST  http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "Rodrigo Oya",
    "dateOfBirth": "1975-07-13",
    "ssn": "090786-1284x",
    "gender": "male",
    "occupation": "House"
}